#Usage
#
# docker build -t b33rsledge/loanmgmt:b001 -f ./Dockerfile.multistage .
# docker push b33rsledge/loanmgmt:b001
#
# Manually run in docker with memoryStorage
# 1 docker run  --rm  -p 8080:8080  -ti b33rsledge/loanmgmt:b001

#-----------------------------------------------------------------------------------------------------------------------
# BUILDER
#-----------------------------------------------------------------------------------------------------------------------
FROM gradle:jdk11@sha256:c4550288e6c3e9723b0d086e25e1efd04c8c8728b09eaf668803442a99f7992b as builder

MAINTAINER Peter Højbjerg

# Copy the entire skycave project to ensure everything is present.
COPY --chown=gradle:gradle ./ /root/service

# Setup workdir to ensure gradle is run from the right location
WORKDIR /root/service

# Cleanup build directory
RUN gradle clean

# Create the server daemon jar file to be used in the image
RUN gradle bootJar
#-----------------------------------------------------------------------------------------------------------------------
# Image
#-----------------------------------------------------------------------------------------------------------------------
FROM openjdk:18-jdk-alpine@sha256:e5c5b35b831a4f655074a25604130ce53e33567b82c8a7204f0e5641b66d477e

MAINTAINER Peter Højbjerg

COPY --from=builder /root/service/build/libs/LoanManagement-0.0.1-SNAPSHOT.jar /usr/loanmgmt/service.jar
COPY --from=builder /root/service/data/ProductMockup.json /usr/loanmgmt/data/ProductMockup.json
COPY --from=builder /root/service/data/LoanFacilityMockup.json /usr/loanmgmt/data/LoanFacilityMockup.json
COPY --from=builder /root/service/data/FeeTypeMockup.json /usr/loanmgmt/data/FeeTypeMockup.json
#COPY --from=builder /root/service/LoanFacilityMockup.json /usr/loanmgmt/data/LoanFacilityMockup.json

#Expose port 8080 as default
EXPOSE 8080

#Setup encoding
ENV JAVA_TOOL_OPTIONS -Dfile.encoding=UTF8

# Required for healthchecks - could be replaced by wget
RUN apk --no-cache add curl

# Required for init process to prevent .jar from beeing started as PID 1
RUN apk add dumb-init

# Add javausers group
RUN addgroup -S javausers

# Add user to javausers group
RUN adduser -S -s /bin/false -G javausers lmuser

# Set ownership to javausers group
RUN chown -R :javausers /usr/loanmgmt
RUN chown -R :javausers /usr/loanmgmt/data

# Setup workdir to ensure later command can find jar file and do ensure yaml file does not need full path in command.
WORKDIR /usr/loanmgmt

# Runs "/usr/bin/dumb-init to have a proper init system in place
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

# set user
USER lmuser

#default command
CMD ["java", "-jar", "/usr/loanmgmt/service.jar"]
