version: '3.4'
# Usage for caveservice

#  -- After update just run deploy again
#   docker stack deploy --with-registry-auth -c lm-stack.yml lmstack

# docker service ls
services:
  mongoservice:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: lmadmin
      MONGO_INITDB_ROOT_PASSWORD: CamelsWithFeelings
    volumes:
      - lm_ms_data:/data/cs/mongo
    networks:
      - lm-network
    ports:
      - 27017:27017
    deploy:
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 1000M
  mongo-express:
    image: mongo-express
    depends_on:
      - mongoservice
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lmadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: CamelsWithFeelings
      ME_CONFIG_MONGODB_URL: mongodb://lmadmin:CamelsWithFeelings@mongoservice:27017
    networks:
      - lm-network
volumes:
  lm_ms_data:
    external: false
networks:
  lm-network: {}
  public:
