spring:
  main:
    banner-mode: off
  data:
    mongodb:
      host: "localhost"
      database: "LoanManagement"
      port:  27017
      password: CamelsWithFeelings
      username: lmadmin
      authentication-database: admin
    messaging:
      exchange: LoanManagement
      routing-key: productupdates
      receive-queue: productqueue
management:
  health:
    mongo:
      enabled: false
    rabbit:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: never
    # Shutdown endpoint configuration
    shutdown:
      enabled: false
  # Actuator endpoint configuration
  endpoints:
    web:
      exposure:
        include: 'health'
server:
  error:
    include-message: always
  port: 8080
debug: true

