name: Copy deploy scripts to digital ocean

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ../script
          cp -TR lm-stack.yml ../script/lm-stack.yml

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SKYCAVEDROPLET_HOST }}
          username: ${{ secrets.SKYCAVEDROPLET_USERNAME }}
          password: ${{ secrets.SKYCAVEDROPLET_PASSWORD }}
          port:   ${{ secrets.SKYCAVEDROPLET_PORT }}
          source: "script.tar"
          target: "/usr/loanmgmt"

      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SKYCAVEDROPLET_HOST }}
          username: ${{ secrets.SKYCAVEDROPLET_USERNAME }}
          password: ${{ secrets.SKYCAVEDROPLET_PASSWORD }}
          port:   ${{ secrets.SKYCAVEDROPLET_PORT }}
          script: |
            tar -xf /usr/loanmgmt/script.tar --directory /usr/loanmgmt
            rm /usr/loanmgmt/script.tar
            ls -al /usr/loanmgmt/script